### PR TITLE
added stances for dex.guru and defiprime 

### PR DESCRIPTION
**Pull request by sneg55**

### CODE REVIEW

**Comment by timbeiko** [comment]
@sneg55 apologies on the delay merging this, but there's now a conflict. Could you please fix it and tag me when it's done and I'll get it merged? Thanks!

**Comment by sneg55** [comment]
@timbeiko  all set

**Comment by sneg55** [comment]
@timbeiko

**Comment by sneg55** [comment]
@benjaminion

**Comment by timbeiko** [comment]
@sneg55 I merged your PR already, dex.guru and defi prime are listed :-)

**Pull request closed without merging**
